= Archive of tweets sent by Laurence Girard as Twitter acccount @nafcnyc

1/25/2022 22:09
We are still strongly considering playing in @NISALeague and in the Open Cup. The major reason we have not made a final decision is that the league has failed to provide us with financial statements. We cannot commit to play in a league that we do not know the financial status of https://t.co/SEtAMO9q81

1/26/2022 20:49
Completely inaccurate. We were not consulted by the league prior to this being announced and we are appalled with Commissioner Prutch’s behavior. We are calling for the resignation of Commissioner Prutch immediately.

1/26/2022 20:49
New Amsterdam FC will be playing in @NISALeague this season. We sent in our @opencup registration to @ussoccer before the December deadline along with the check for our Open Cup performance bond and registration. NISA’s announcement that we are not playing in the Open Cup is

1/26/2022 20:57
@MichaelB_96 Yes just messaged you

1/26/2022 23:28
@aghease Games will primarily be at Galeic Park this year! Finally!

1/26/2022 23:28
@aghease Club trains in Tribecca at pier 40 as well

1/27/2022 4:58
@jdhartman24 @NISALeague @opencup @ussoccer At the time we said we were considering playing we were still considering it. At the time we said we were playing (24 hours later) we made a final decision. Hope this makes sense.

1/27/2022 5:01
@jdhartman24 @NISALeague @opencup @ussoccer Pretty tough to agree to play in a pro league that hasn’t provided financial statements to us or a budget.

1/27/2022 5:14
@PaulLapointe98 @NISALeague @opencup @MichaelB_96 @KnightsWhoNISA @FirstTeamPod @ussoccer USSF needs to force NISA to provide financial statements in a more timely fashion to its clubs that are spending millions of dollars to field teams

1/27/2022 5:16
@FlowerCityUnion At least 50 if Commissioner Prutch keeps up the shannanigans of not providing our club with financial statements or a budget for this upcoming season!

1/27/2022 5:19
@NISALeague Interesting post 🤨

1/27/2022 5:21
@tsuliman @NISALeague Curious how a team that didn’t exist last year qualifies for a cup, but our team that has played for 3 seasons, sent in its US open cup check in December, and is planning to play this upcoming season doesn’t get announced as a team that’s playing in the cup.

1/27/2022 6:09
@DuchessTacoCOT @taco_x86 We sleep quite well! We have dozens of angel investors who are investors in our club and are very thankful to our sponsors for supporting our mission of having a social impact through sports including our new youth academy that had over 1K players register for a tryout.

1/27/2022 6:10
@DuchessTacoCOT @taco_x86 Many professional sports teams are sponsored by or have partnerships with healthcare companies! Red Bulls - Horizon BCBS, nycfc new york presbyterian, and many other examples.

1/27/2022 6:52
@mojodean @taco_x86 @DuchessTacoCOT We believe NISA will succeed under the right leadership. If it fails, I’m sure you can guess at what the other options are to play soccer in the US. Our investor group is also in the process of acquiring a club in Europe.

1/27/2022 7:10
@eastsidekate @phat7deuce We were really looking forward to that local rivalry.

1/27/2022 7:13
@AndyKingSoCal @phat7deuce John Prutch is often criticized by NISA team owners for being a liar. He needs to resign. You can't have a a commissioner in charge who consistently lies to owners and acts in his own self-interest of himself and his children who work for the league. #prutchneedstoresign

1/27/2022 7:18
John Prutch is trying to push NAFC and CHAC out of the league despite being two strong brands in major markets that finished 4th and 5th last season. Only in America would one man's personal agenda determine a team's league status rather than pro/rel like in Europe.

1/27/2022 7:35
He is scared that the other team owners might agree with us that we might need a new leadership team and a new commissioner at NISA. He is trying to push us out in an attempt to keep himself, his son, and his daughter employed by NISA.

1/27/2022 9:07
@ProtagonistUSA @KnightsWhoNISA ask John Prutch about his fraudulent representation from October to “invest $1 million into Chicago House within 60 days” from either the league or Football Investments (which he and Friedland control) which he never followed through with.

1/27/2022 12:20
Someone please ask me about when the LA Force owner changed venues at the last minute and made us play at a facility without locker rooms that didn’t meet PLS. League didn’t issue a fine. Lights went off in 2nd half and LA awarded win. Ask yourself - why didn’t LA get fined? 🧐

1/27/2022 14:24
@RedTheWhiteBoy You might want to ask NISA who owns the league and see what they say.

1/27/2022 14:45
@NISALeague has provided funding to teams in the past during the pandemic which is wonderful! Do you think the commissioner would try to fund expansion teams A and B instead of founding teams C and D just because C and D think he and his family could be doing a better job? I do

1/27/2022 14:49
@NISALeague should do a $5 million RegCF campaign from fans on We Funder. When we suggested this to commissioner Prutch he refused and said he didn’t want the public to see NISA’s financials. We think fans should own part of the league and have a vote.

1/27/2022 14:49
@Wefunder

1/27/2022 14:59
@phat7deuce Obviously if the teams had a vote and the fans did and there was some issue where 5 teams vote one way and 5 vote another way, the fans would be the deciding factor now wouldn’t they?

1/27/2022 15:02
@cjcoreschi You’ll thank us later when new leadership is put into NISA that grows the league successfully. If only you knew my friend

1/27/2022 17:12
Thank you @ussoccer for your response regarding the @opencup. https://t.co/CgrCOT14I5

1/27/2022 17:36
Great thought - it’s actually exactly what we have been trying to do!
BUT….
The commissioner of @NISALeague does not want us to compete in the league fairly 

Not sure the commissioner has considered there are 100s of people affected by his personal vendetta with 1 person… https://t.co/NNnvypkvzW

1/28/2022 8:19
@NISALeague is now working with us to have New Amsterdam play this season. Hopefully we can move forward with @NISALeague to play some soccer. Looking forward to the season. Thank you @NISALeague 🙏⚽️🏟

1/28/2022 8:47
@ProtagonistUSA @THEDanVaughn @NISALeague One reason among others that we didn’t pay the remaining small portion of the league dues yet is because they refused to provide the financial statements when we requested them.

1/28/2022 8:56
@skidawgkc22 @ProtagonistUSA Is it ok for the commissioner to lie to a club and blatantly say his group is going to invest $1 million within 60 days into a club and then not follow through? Clubs rely on such statements for financial planning when these types of statements are made.

1/28/2022 9:16
@tsuliman @ProtagonistUSA @NISALeague Agree but that’s not us. We just launched our academy with over 1,000 players registering to trial and we will have at least five youth teams in EDP this year with 100 players. I think you’ll see us become one of the largest academies in NY. We’re in it for the long term!

1/28/2022 9:29
@IPlayWithTrucks @NISALeague Ask us anything we’re an open book. The only way to improve a business or a league is to openly and transparently discuss the issues at hand so we can brainstorm solutions!

1/28/2022 9:30
@IPlayWithTrucks @NISALeague Keep the constructive criticism coming! We actually love it. Rule number 1 is business is listen to your biggest critics. Nothing more valuable than negative feedback!

1/28/2022 9:45
@IPlayWithTrucks @NISALeague Thanks sir

1/28/2022 10:43
@srlwizfan @ProtagonistUSA @NISALeague Amen brother to the first sentence in your post. The league is owned by one team owner that owns around 60-70 percent of the equity. The league was supposed to be equally owned by all of the teams similar to the premier league. But it’s not.

1/28/2022 10:46
@srlwizfan @ProtagonistUSA @NISALeague Each team owns around 2-3 percent. So basically close to nothing is owned by the teams. Our club has called for the cap table to be reset and the equity equally distributed to all the clubs.

1/28/2022 12:06
@phat7deuce Phil Anschutz

1/28/2022 13:47
@OpenSoccerFdn https://t.co/x0aLvfepeT

1/28/2022 15:16
More nonsense from @NISALeague. We told them we were 100% ready to play, pay league dues etc. and now they are imposing rules against NAFC that they are not imposing against other teams. That's not how this works. All NISA teams should be subject to the same rules. @ussoccer

1/28/2022 16:44
Our $250,000 performance bond has been in place all of last season and is in place ready to go for next season. Can’t speak for other @NISALeague teams, but we are ready to go! See below. https://t.co/RYNccFPyL5

1/28/2022 16:44
@opencup @ussoccer

1/28/2022 18:03
Guess who! Name your guess below! https://t.co/QdWcrjKSue

1/28/2022 18:09
Guess how much money we made in 3 seasons by flying around the country instead of low-cost sustainable travel as you would have in lower division London based football: Multiple choice:

1) +$3M
2) +$2M
3) +$1M
4) break even 
5) -$1M
6) -$2M
7) -$3M

Leave your guess below! https://t.co/Y4cNr6ghUM

1/28/2022 18:11
Our point is Division III football needs to be local and regional. In London clubs at this level travel no more than 3-5 hour bus trips!

1/28/2022 18:12
@cmtake13 @JDallessio @NISALeague @ussoccer There are rumors floating around that our owner played with Messi in 2010 at Red Bulls academy

1/28/2022 18:20
@JDallessio @cmtake13 @NISALeague @ussoccer He actually had two jobs. He was supposed to be working full time for our club since we were paying him $120K/year but he secretly kept his old job at Manhattan Soccer Club. That’s why we fired him. He wasn’t giving his full attention to the club.

1/28/2022 18:23
How about a non-profit pro league where all of the clubs have an equal vote?

1/28/2022 18:25
Is it shocking to anyone else that commissioner Prutch hasn’t given a personal phone call to NAFC or CHAC ownership in weeks? How about a thank you for spending millions developing the league that employs you during a global pandemic? @NISALeague @KnightsWhoNISA

1/28/2022 18:28
One of the other NISA owners offered to provide funding to the league which they could then invest into a club to help them play this season. The chairman of the board said no. How insane is that? He wants less teams playing pro soccer?

1/28/2022 18:29
NAFC and CHAC have still not been provided with league balance sheet, profit and loss, or budget for NISA this season despite NAFC confirming its desire and intention to play this season. @NISALeague

1/28/2022 18:33
This is the only structure worth talking about and trying to emulate. https://t.co/vWZy7gRLU2

1/28/2022 18:34
@KnightsWhoNISA  @NISALeague @ProtagonistUSA

1/28/2022 18:47
@kiserstallings @NISALeague @ussoccer https://t.co/rOgf41SBjl

1/28/2022 18:50
NISA pays Bien $600K/year for production which generates no revenue and Bien won’t even tell them how many people are watching so they can’t sell any sponsorships! Commissioner Prutch - nice job with the stupidest sports deal in American history. Better to put the games on UTUBE https://t.co/5uKdp8sYJF

1/28/2022 18:54
Does anyone else think it's a conflict of interest that 
@NISALeague's attorney  is also the personal attorney to the LA Force and Bob Friedland the chairman of the board? @NISALeague instead of blowing $600k/yr to Bien, get the teams independent + unbiased legal counsel.

1/28/2022 18:57
I love flying around the country while earning no media revenue - very rational. In league 2 in England the clubs get $1.2M in media revenue and have local low cost travel

1/28/2022 19:01
https://t.co/hZ4Np1dvrg Quote from the article comments “The LA Force owner is one of the main investors in NISA… he bends rules all the time and NISA lets him get away with it all the time. He also hired the commissioner of the league… just saying” @NISALeague LA owns aprx70%

1/28/2022 19:03
@OldBaeBrigade We hate trump

1/28/2022 19:03
@mplscitysc @DionDCFC @phat7deuce @WhiskeyIsFine @NipunChopra7 Yuppppppp

1/28/2022 19:05
@OldBaeBrigade We all just love soccer man what with all the hate, just a ball and a goal

1/28/2022 19:07
@OldBaeBrigade By the Way I love your club the bobcats we are huge fans of

1/28/2022 19:08
@OldBaeBrigade https://t.co/YcJ8eyAt07

1/28/2022 19:09
If I had to guess, I would say that the Prutch family is going to use the Detroit settlement money to pay their own bills rather than giving funding to chicago house and the founder of the league To run one of the best brands in the league @ChicagoHouse_AC

1/28/2022 19:16
@cjcoreschi https://t.co/VVrzqJmSye

1/28/2022 19:31
@bydaveroberts What do you propose instead sire ? You a fan of pro / rel? https://t.co/eADxaQ1LhC

1/28/2022 19:33
Friedland still could be forced to give @NISALeague $310K of a credit line he promised the league in exchange for the majority of the equity. Shocking that he gets to keep his equity stake without following through immediately on this funding commitment.

1/28/2022 19:42
@cmtake13 @bydaveroberts https://t.co/0zHY3DhkRa

1/28/2022 19:45
Our ownership group is available to answer any and all questions about NISA's structure - the pros and the cons. Literally ask us anything and let's redesign lower division soccer the right way with input from the fans. @THEChrisKessell

1/28/2022 19:46
@bydaveroberts @cmtake13 apologies brother, just sincerely wanted your opinion

1/28/2022 19:47
@bydaveroberts @cmtake13 can we send you some free gear? dm us your address

1/28/2022 19:49
More NISA teams = more league dues = more teams so the league can keep 8 teams = the Prutch family can keep getting paid from league dues. Say anything bad about the Prutch family / Friedland and boy you are in trouble.

1/28/2022 19:50
If the Prutch family / frieldand had any interest in building a league, then they would not be trying to kick Chicago and New Amsterdam out of the league. Two clubs with amazing brands in major markets that are willing to spend money building lower division football clubs.

1/28/2022 19:55
When the 1st, 4th, and 5th place team are considering leaving the league you know you have a problem. Interesting how after 1st place team left, LA Force (2nd place team) wants to kick out 4th and 5th place team after 1st place left. Maybe they think it will help them win league https://t.co/ioaGStzn4t

1/28/2022 19:55
Guess who is in the pic

1/28/2022 19:58
@Vikingbob69 https://t.co/8NzAzkGWI5

1/28/2022 20:02
@NISALeague https://t.co/QhDSt3Vf50

1/28/2022 20:04
Good guess but listen dude it's someone that I don't like  who is not treating our soccer team really good

1/28/2022 20:06
what would you pay for a documentary on Netflix of @NISALeague - it's so funny that we have thought about making a documentary so many times. I admire all the entrepreneurs/owners in this league except 1. They love the game. Will be biggest revenue source BY FAR! @netflix ?

1/28/2022 20:07
@DuchessTacoCOT Honestly I consider myself to be starting a soccer uprising or revolution. @NERevolution are you with me?

1/28/2022 20:08
@Vikingbob69 I was holding back yesterday, but I just have some much drive and conviction over fixing lower league soccer truthfully. I really want to tell you everything. https://t.co/DJXSQNRmjv

1/28/2022 20:10
@Vikingbob69 @NISALeague @netflix Oh the first 6 beers are on us my friend. https://t.co/3ZYxkbVPl8

1/28/2022 20:19
@taco_x86 PLEASE ASK ME! https://t.co/ZCWIBQ60vh

1/28/2022 20:20
@ACharmCitySG @MDBobcatsFC I love the bobcats. I am not talking shit. We think they are a great team and we love their ownership group. Nice jerseys, great players.

1/28/2022 20:20
@DivisionZero4US @NISALeague @netflix nope

1/28/2022 20:58
@taco_x86 Club 9 (John Prutch entity) owns some equity and so does Mission Series (Bob Friedland's entity) that get votes in addition to the teams. If you think that each team has 1 vote, that could not be further from the truth. Friedland also has veto power.

1/28/2022 20:59
@taco_x86 Amen brother. It should be ONE CLUB = ONE VOTE! https://t.co/n1bMBEtBIb

1/28/2022 21:00
@taco_x86 Honestly I don't mind your comedy. It just motivates me to try to get a bit better at goalie. Yea I'm not the best keeper in the world, but I love the game! I'll try to work harder mate.

1/28/2022 21:01
@Vikingbob69 @NISALeague @netflix @PhxRisingNation Hey give me the address will send now. DM us and we will send those Pizza's over right now. Serious.

1/28/2022 21:02
@taco_x86 I don't think he VETOED anything yet, but it doesn't make me feel good that he can. I think the reason they didn't fine him when the lights went off at the game against NAFC is because he is such a big financial backer of the league.

1/28/2022 21:03
First 10 soccer fans to reweet this get $50 of free pizza delivered in the next 60 minutes courtesy of NEW AMSTERDAM FOOTBALL CLUB. THANK YOU SOCCER NATION! https://t.co/gt3OFKo58e

1/28/2022 21:10
Nothing like shopping for an English football club to support and grow while fixing lower division football in America. Can’t wait for NAFC to have a sister club in the UK. NAFC says hello mate from Football Heaven in The UK this evening! https://t.co/M027iBnRkh

1/28/2022 21:11
DM us to claim your PIZZA!

1/28/2022 21:12
@green_loon @NISALeague https://t.co/nY0UO3YFpV

1/28/2022 21:12
@NISALeague https://t.co/WUTl0H0A4S

1/28/2022 21:14
@not_th_messiah Is it me? How did you know my friends send this all the time?

1/28/2022 21:14
@not_th_messiah https://t.co/AU0SerFXwH

1/28/2022 21:18
@honestlyboxey Yes master we are doing it now. I am sorry that we displeased you. https://t.co/ciJABltznR

1/28/2022 21:18
@green_loon @NISALeague https://t.co/PwkkbvvjMO

1/28/2022 21:19
DMS ARE OPEN TO CLAIM THAT PIZZA!

1/28/2022 21:21
@cameronmreed yes please DM us your Venmo

1/28/2022 21:22
@Vikingbob69 @PhxRisingNation https://t.co/rVcpdrblCB

1/28/2022 21:23
@DivisionZero4US @NISALeague @netflix @ussoccer 1) Demand that John Prutch resign and appoint Ron Patel or Ron Gilmore as commissioner 
2) League settles with NAFC. Right now the issue is that NISA is demanding we do a $1M performance bond (they are not asking any other team to do this) and the requirement is only $250K.

1/28/2022 21:23
@DivisionZero4US @NISALeague @netflix @ussoccer Then the league needs to use Detroit settlement money to fund Chicago and a bit NAFC. Both NAFC and Chicago play in Open Cup. Use Detroit settlement money to fund two sick clubs instead of paying Prutch family bills.

1/28/2022 21:24
4 Step plan to fix NISA:
1) US Soccer demands Prutch family resign
2) Detroit settlement money funds Chicago House and the founder of the league Peter Wilt
3) NAFC and Chicago play in NISA and 2022 US Open Cup
4) Sue Friesland to get equity back and distribute evenly.

1/28/2022 21:28
@ussoccer needs to protect whistleblowers like us who want things to be transparent for the benefit of the game. WAKE UP @ussoccer - multiple NISA teams NISA announced playing in the Open Cup have told me they are undecided if they are even playing NISA. Stop lying John - resign. https://t.co/OtVvMuo6ml

1/28/2022 21:29
@taco_x86 Frieldland and Prutch did do something. Their owner George is actually a very nice man. He did reimburse Cal United for their expenses. George is one of my favorite owners and a very nice human being. His family is also very nice.

1/28/2022 21:30
@taco_x86 The issue is that the league tried to fine George and make the stars put $100K in Escrow. It's a double standard that they hurt George, but then they did not fine the LA Force when they played at a facility in a public park and couldn't leave the lights on. Double standard!

1/28/2022 21:32
Let's fix NISA League and write a new constitution together written by teams and fans. If you think Prutch should go please #prutchout https://t.co/jSjhUD8KQ8

1/28/2022 21:33
@CTSoccerMike We're good with whatever style you want

1/28/2022 21:35
@LOLtimore They should fund Chicago. It was always launched as a project to help the league and nothing else. The club is happy to let the league own the largest piece of equity in the club. We don't want to own the club, I want it to simply benefit the league and the US soccer landscape.

1/28/2022 21:37
@LOLtimore dm us for the pizza, ya we are open to selling it or giving it to the league

1/28/2022 21:37
@LOLtimore we just want the club to succeed for the benefit of the league, the players, and the US soccer Landscape

1/28/2022 21:38
@taco_x86 https://t.co/ddOBa6SEHa #prutchout

1/28/2022 21:38
We want in on the Open Cup. #prutchout https://t.co/R76MifTsLx

1/28/2022 21:40
WE THE PEOPLE DEMAND A TRANSPARENT PROFESSIONAL SOCCER LEAGUE THAT ALWAYS LOOKS OUT FOR THE INTEREST OF THE CLUBS AND NOT ENRICHING THE POCKETS OF THE COMMISSIONER AND HIS FAMILY. WE AIM TO GROW THE GAME IN THE US FOR THE BENEFIT OF PLAYERS, FANS, AND COMMUNITIES! https://t.co/t71Mrq6twH

1/28/2022 21:45
FUCK IT LETS GO CRAZY. WHO THE FUCK WANTS SOME MORE PIZZA? DM US YOUR VENMO OR ADDRESS WE GIVING OUT PIZZA ALL NIGHT BABY. #socceruprising https://t.co/jiaMNzEhSN

1/28/2022 21:51
https://t.co/R4Ipjxe4jQ

1/28/2022 21:54
@KnightsWhoNISA @KnightsWhoNISA @NISALeague

1/28/2022 21:55
@RowdiesFaithful @taco_x86 https://t.co/VLUwcl6UOX

1/28/2022 21:56
@RowdiesFaithful @taco_x86 https://t.co/6MPdqfWglD

1/28/2022 21:59
Come on guys ask me some juicy questions and let's fix this league.

1/28/2022 21:59
@Vikingbob69 @taco_x86 @MichiganStarsFC yo my guy George is a nice human too

1/28/2022 22:00
@nolanater thank you master, amen https://t.co/i6B9PFbkwo

1/28/2022 22:05
@Vikingbob69 @taco_x86 @MichiganStarsFC Michigan stars owner he’s a nice human

1/28/2022 22:06
@taco_x86 Cheers MATE https://t.co/FPFP2bGdkR

1/28/2022 22:16
I challenge John Prutch to a public debate broadcast on Facebook live where we debate the issues with the league in a transparent way in front of all @NISALeague fans. If he declines he has something to hide he doesn’t want you to know. https://t.co/7ZpuhjkRyR

1/28/2022 22:16
@cmtake13 It’s full blown ready to go had 1,000 players registered and will likely have five teams

1/28/2022 22:24
@RedTheWhiteBoy More to come.

1/28/2022 22:24
@zeeinthedee @taco_x86 getting to it

1/28/2022 22:25
@Vikingbob69 @PhxRisingNation @PHXRisingFC we ain't going to sleep till everyone gets a pizza. YOU GET A PIZZA AND YOU GET A PIZZA AND YOU GET A PIZZA

WE LOVE YOU SOCCER NATION

1/28/2022 22:28
John Prutch needs to GTFO and stop telling Peter Wilt what to do. He is the founder of the league and has launched more pro clubs than anyone in the world. John Prutch is a useless fuck that never played soccer in his life. I'm sorry. It needed to be said. THANK YOU PETER!

1/28/2022 22:28
https://t.co/RQSbsQguJN

1/28/2022 22:29
@nolanater @nisa Dude they are clowns. I could run the league in my sleep compared to these clowns. One of the biggest team owners (I can't say who) said that everyone in the international soccer community thinks the Prutch family are clowns. And that's a direct quote.

1/28/2022 22:30
Listen to how sad this is. When I email all the other team owners Mr. Prutch does not like it. He really doesn't understand that in the age of the internet it is about information sharing and transparency. Oh no please don't send another email to your fellow shareholders! https://t.co/6ls3LEebjo

1/28/2022 22:32
I swear I will liberate lower division soccer for the fans and make the league a success. Not with Mr. Prutch in charge. LFG! https://t.co/t5kg0VJWvz

1/28/2022 22:35
@NYCosmos  we love ya, but can you please just launch a crowdfunding campaign and let your fans invest so they can see the team they love play? It's called We Funder -  get with the program so we can get the NY Darby going again. The people love it. 5K tickets for sure.

1/28/2022 22:37
@NISALeague let me know when you are ready for Mr. Wilt to fix the league. He is waiting and ready. John get the fuck out, thanks. Founders know best.

1/28/2022 22:38
@RaffaeleLafayet I am ready to spend the cash. I just don't want a moron as the commissioner. Thanks for the question.

1/28/2022 22:40
@JustinVibbs https://t.co/yF01FfOaYp

1/28/2022 22:41
@JustinVibbs https://t.co/46Ne0M05sW

1/28/2022 22:42
I asked and demanded the league to call our club tonight to have a settlement conference. They refused to have a civil conversation. Shows their poor leadership. @NISALeague shame on you.

1/28/2022 22:42
More to come tomorrow my friends. It is 3:42AM in London! @NISALeague needs to shape up and start doing the right thing.

1/28/2022 22:43
If we didn't send you a pizza, we got you tomorrow! We got thousands of requests!

1/28/2022 22:43
@BADEnoughDesign nice nice nice thank you thank you thank you

1/28/2022 23:25
Wow I just had an insane conversation about the future of lower division soccer. Mind blown. More to come. https://t.co/4UDYH8OvY1

1/28/2022 23:28
@KnightsWhoNISA https://t.co/OWYrW8oOIY

1/28/2022 23:29
@OldBaeBrigade @KnightsWhoNISA https://t.co/bemRE7MJkX

1/28/2022 23:30
@taco_x86 @KClayFootball https://t.co/opq2lJFFe5

1/28/2022 23:32
@Vikingbob69 Do you know much pizza I could give out for $750k a year ?

1/28/2022 23:33
@taco_x86 https://t.co/Gmoon6O8T6

1/28/2022 23:35
@taco_x86 Going to a game for our new English club tomorrow. I gotta focus on the soccer uprising! I can’t sleep this is sooooo exciting https://t.co/Idzy02rg1b

1/28/2022 23:36
Does anyone think it’s rational that we spent $30K to fly across the entire United States to play against LA Force at a public park and then the lights went off in 65th minute causing us to lose? Please I beg you if I ever do this again murder me.

1/28/2022 23:53
@cameronmreed Sick!

1/28/2022 23:53
@cameronmreed https://t.co/jVOy8l3Iga

1/28/2022 23:55
@919zac Agree it should be non profit

1/29/2022 0:00
@WhiskeyIsFine @ChattaGooner @ChattanoogaFC It’s 100 percent illegal to use international amateurs and it needs to stop. The fact NISA is even considering it shows leadership is incompetent

1/29/2022 0:04
@TouchlineTakes https://t.co/VjWIZCPyCY

1/29/2022 0:05
@jze98 https://t.co/CjJyqpmbG4

1/29/2022 0:07
One of my favorite business and life quotes I came up with - the path will reveal itself at the most uncertain time.
#socceruprising https://t.co/hp5OOeZszi

1/29/2022 0:15
Oh yea that’s a good point https://t.co/aZhauPvqAT

1/29/2022 0:16
normally we are more on LinkedIn app but the bird app is really fun for The Soccer.

1/29/2022 0:19
@PhxRisingNation Yea baby!

1/29/2022 0:25
@DSzetela14 @whitelaw827 Amen about having players involved look at the athletes unlimited model @AthletesUNL

1/29/2022 0:30
Commissioner Prutch in case you forgot about the two clubs that saved your league during a global pandemic and paid your family salaries give me a call. Haven’t heard from you in a few weeks on the phone. @NISALeague https://t.co/wSFXyFPHfM

1/29/2022 0:31
@JosephSlowvak I love it

1/29/2022 0:31
@JosephSlowvak We are gonna turn this into a special edition t shirt I think

1/29/2022 0:34
This is the irony. @NISALeague is obsessed with being pro league sanctioned by US Soccer but then half the clubs beg to use international amateurs which is illegal. Talk about irony.

1/29/2022 0:36
@PhxRisingNation Wow that looks yummy

1/29/2022 0:38
@PhxRisingNation https://t.co/tu87Z853J0

1/29/2022 0:40
Can I get a NEW AMSTERDAM TILL I DIE?
about to watch Sunderland till I die and I’m pretty excited

1/29/2022 0:41
Is New York or Chicago Pizza better? That my friend is the question

1/29/2022 0:48
@arranpitch https://t.co/IcAGTDXPdV

1/29/2022 0:50
@Vikingbob69 @PhxRisingNation Dale is our clubs favorite word at training!!! DALE

1/29/2022 0:51
@wayt100keen Miss I know you are probably talking about the TV show and not our lower division football club. But the irony of this is incredible since our co founder is named Max and he would love To be shipped off to London. Thank you for this post it made me smile.

1/29/2022 0:54
https://t.co/0QLEW8TVbu does anyone know if this still exists? Met the founder a decade ago and would love to support it

1/29/2022 0:59
What should our mascot be?

1/29/2022 1:00
@RE84276308 Yo we just went to your game it was amazing here is a pic https://t.co/7fqFNkchPZ

1/29/2022 1:01
@CTSoccerMike One horse sized duck https://t.co/8C7tSDgBbV

1/29/2022 1:10
Stumptown got funding in the past around $800K I believe. Yet the founder of the league wilt asks for a fraction of this for Chicago and Prutch and friedland try to push NAFC and CHAC out of the league and push to deny funding request. Founders deserve more respect.

1/29/2022 1:32
@shutupgalen Obviously we need it which is why I’m in England

1/29/2022 1:36
@ThaBlackUnicorn @DionDCFC @becadair @taco_x86 https://t.co/jjZeDOOsDc

1/29/2022 1:40
@Vikingbob69 https://t.co/YnX2LWPaSe

1/29/2022 1:42
@honestlyboxey $1M, $400k upfront and $150K a year thereafter. John Prutch and friedland negotiated it with his attorneys without anyone else. They presented it And made us vote on it on same board call. Bad deal for NISA IMO. Rammed it down our throats. No time to think about it IMO.

1/29/2022 1:43
@honestlyboxey They should have presented the legal analysis 48 hours in advance of a board call and then given us some time to review instead of making us vote instantly

1/29/2022 1:44
Will be shocked if NISA has 8 teams. Many of the teams Nisa claims are playing are not sure. Guess they need new Amsterdam and chicago after all. Prutch will come begging soon https://t.co/F9z9i3PpFJ

1/29/2022 1:47
NISA settlement with Detroit is bad deal for NISA. My guess is Detroit made a ton of fraud claims against Prutch. Prutch won’t tell me what the claims are that Detroit had against the league and him. My guess is that’s why NISA took $1M instead of $2.5M.

1/29/2022 4:02
@Nic_Freiri My man this is truly funny

1/29/2022 4:04
@RaffaeleLafayet @THEChrisKessell Each club has 2-3 percent equity. League dues this year $100K. $250k to join NISA. Many clubs do not pay league dues all at once but pay overtime or late. The league does have debt. Yes the league has been late with paying vendors and refs. I want the league to finance CHAC

1/29/2022 4:07
@theactualsoccer @DivisionZero4US @NISALeague @netflix @ussoccer I think they should fund chicago Peter did a great job

1/29/2022 4:08
@ChattaGooner @tomg910 @J_Kaley https://t.co/sn0hmXSzIy

1/29/2022 4:11
https://t.co/7Cmdz5ZZrd

1/29/2022 4:15
Soccer uprising https://t.co/NGQ0V5mLvJ

1/29/2022 4:16
@AndrewDettmer You mean a country where at least some financial support is provided to lower level clubs instead of zero and if a club gets promoted they have a shot at some media and academy revenue? But yea lower league clubs could use even more help even in the Uk, amen

1/29/2022 4:20
@TaylorTwellman Amen

1/29/2022 4:21
https://t.co/WBt16YNhx6 https://t.co/6y2FrTv5Ll

1/29/2022 4:27
@theactualsoccer @DivisionZero4US @NISALeague @netflix @ussoccer Need to cut budget move to smaller venue

1/29/2022 4:32
@cjcoreschi Incorrect sir

1/29/2022 4:33
@cjcoreschi Thanks for compliment

1/29/2022 4:34
@kkfla737 @ProtagonistUSA https://t.co/k9Hd5KUbT7

1/29/2022 4:35
PS Stumptown isn’t playing this year

1/29/2022 4:36
@RaffaeleLafayet @THEChrisKessell Transparency wins the day

1/29/2022 4:39
Any @NISALeague owner that plays under the leadership of Prutch has either:

1) lost their mind 
2) has a sick fantasy where they enjoy burning 6-figure amounts of cash
3) their level of optimistic thinking will ultimately result in their financial downfall 
4)enjoys chaos

1/29/2022 4:54
@WhiskeyIsFine Yes sir it’s being paid over next 2-3 weeks. Apologies for delay. It’s rough to play in a league with an unsustainable business model that has no media revenue and cross country travel. By the way the league hasn’t paid it’s stadium bill to Chattanooga either

1/29/2022 5:01
Hey @NISALeague Insanity is doing the same thing over and over and expecting different results.

1/29/2022 5:18
@NISALeague commissioner needs to resign https://t.co/WoG6Yh8bUf

1/29/2022 5:20
https://t.co/ztoBj9I7kJ

1/29/2022 5:21
@KClayFootball https://t.co/cCwuFUl5oI

1/29/2022 5:24
@NISALeague #prutchout - commissioner needs to resign. https://t.co/UEn96JCEj6

1/29/2022 5:24
@SeriousRebrand https://t.co/cxesXmqfvo

1/29/2022 5:27
What’s better burning $1 mil on unsustainable pro league or spending $300k a year on sustainable semi-pro plus investing $200k in a youth academy and local community ? #sustainablesoccer

We are here to build something that lasts 100 years. Not get rich quick before 2026 plan.

1/29/2022 5:29
If the commissioner doesn’t call me today after weeks of silence you really know the only person he cares about is himself and his family getting paid. Real leaders try to resolve things. He ignored my calls. GTFO commissioner Prutch. @NISALeague stop holding up open cup. https://t.co/6j9GR5lYug

1/29/2022 5:40
@mojodean Thanks for the concern. At a sexy breakfast right now before an English football match

1/29/2022 5:42
@mojodean Oh thanks for the tip, your club is sick

1/29/2022 6:53
@TheUSSocProject @NISALeague @ChicagoHouse_AC @DetroitCityFC @CalUtdStrikers @LosAngelesForce @StumptownAC @MDBobcatsFC Uh Nisa is in fifa?

1/29/2022 7:34
@RedTheWhiteBoy ASSET 10000 percent

1/29/2022 7:39
@scottyk0828 @NISALeague It’s not pro just because you blow tons of cash , agree

1/29/2022 8:16
@IPlayWithTrucks Lawyer only

1/29/2022 9:53
@ThaBlackUnicorn @mojodean https://t.co/HHdZWzYYHX

1/29/2022 11:23
A @NISALeague employee thinks that one of the teams NISA claims is playing doesn’t qualify for PLS for net worth and made a deal with @NYCosmos to qualify. Why does that team get to play in @opencup but NAFC doesn’t? I know which team it is.

1/29/2022 11:38
@MichaelB_96 @NISALeague @NYCosmos @opencup If I had to guess based on the information provided it means Rocco may be functioning as the PTO on paper for that team so they can meet PLS

1/29/2022 13:22
@DJBisogno @DionDCFC https://t.co/CYqWTMgABf

1/29/2022 14:03
@NISALeague we would like to send you a Pizza (peace) offering. What address should we send chicago deep dish pizza to? Seriously I’ve been asking commissioner Prutch for a settlement conference for a couple weeks and haven’t gotten him to agree. What do you like as a topping? https://t.co/Gz3wygSNIc

1/29/2022 17:48
Big news coming within the hour. Stay tuned. https://t.co/PdYquIY4b4

1/29/2022 18:19
@dumpster_bear https://t.co/Kx8ldvSzNH

1/29/2022 18:32
@taco_x86 @ToledoWalleye https://t.co/zslQBvmo4d

1/29/2022 18:37
@mikeireland @ESPNFC @FOXSoccer https://t.co/TNu9pmcPlw

1/29/2022 18:38
Here is a hint: https://t.co/EYR1mIbDF7

1/29/2022 18:39
Honestly is there any possibility we could ever get 3,000 fans a game at Gaelic park for a NISA game or is this just some sort of sick fantasy? Tell me really.

1/29/2022 18:45
@ombreakker What is realistic in your view

1/29/2022 18:46
@mojodean https://t.co/N1ef4c4UmL

1/29/2022 19:14
Announcement will be delayed an hour or two sorry m8

1/29/2022 20:43
Reposting the link to our new pizza party t-shirts! Thank you fans! https://t.co/F68obL6QOe https://t.co/sxamDylETr

1/29/2022 21:01
@richransom21 https://t.co/gLSnicAQqX

1/29/2022 21:29
@Valiant_33 @dominos will you sponsor us!?!?!

1/29/2022 21:31
@THEDanVaughn https://t.co/1CvqJaksTL

1/29/2022 21:31
@J_Kaley @THEDanVaughn https://t.co/oqSkbimd7C

1/29/2022 21:36
Nothing like football talk at a London hotel bar. https://t.co/Rxi2E3pEEB

1/29/2022 21:43
@jgbrass @THEDanVaughn https://t.co/VP54yUzwXQ

1/29/2022 21:46
Do you think all NISA clubs should be subject to the same financial rules in terms of the size of their performance bond?

1/29/2022 21:48
@NGSDetroit https://t.co/r8jtAJe7m1

1/29/2022 21:49
@NGSDetroit Love your club, amazing, win USL for us baby!

1/29/2022 21:50
@NISALeague should have fans and athletes represented on the Board of Governors. Agree or disagree?

1/29/2022 21:54
@zfish04 1) no until this year 2) working on it 3) no but better than last two seasons 4) Yes baby! The 100 year plan

1/29/2022 21:55
@mikeireland @NISALeague Athletes and fans shouldn’t need to pay to get a seat at the table. #ourleague

1/29/2022 21:55
https://t.co/tx5dFiupYw

1/29/2022 21:56
@GreatGatzke What’s that? It sounds fun

1/29/2022 21:57
@zfish04 https://t.co/UNa4zCPNWT

1/29/2022 21:58
@TimHowardGK we need a new goalkeeper coach. Our club loves you.

1/29/2022 22:01
@mikeireland @NISALeague One vote for athletes and one vote for fans on all issues. One athlete elected by players and one elected through annual fan poll

1/29/2022 22:04
@SoccerCoachJB Love this

1/29/2022 22:04
@ChattaGooner @NISALeague It would be nice if the commissioner would pick up the phone and call our club

1/29/2022 22:05
@mikeireland @NISALeague Sure the board can be like the electoral college

1/29/2022 22:07
@GusMacker1 @taco_x86 @mikeireland @NISALeague https://t.co/DkQKPDSwlk

1/29/2022 22:11
@albert_is https://t.co/B81o4Wu7Rx

1/29/2022 22:27
@shellyayers82 Yup

1/29/2022 22:28
@gr8ftblr @RaffaeleLafayet Ty

1/30/2022 7:14
@taco_x86 No I haven’t

1/30/2022 7:16
@NISALeague https://t.co/42irCm1i2S

1/30/2022 7:16
@NISALeague https://t.co/LASsoTSwNC

1/30/2022 7:19
@NYCosmos @DetroitCityFC @NYCosmos @MDBobcatsFC @oaklandrootssc @TheMiamiFC @FlowerCityUnion @SyracuseAC @valleyunitedaz @CalUtdStrikers @MichiganStarsFC @ChattanoogaFC @LosAngelesForce @ALBION_SanDiego

1/30/2022 7:21
@ussoccer @opencup

1/30/2022 7:34
@taco_x86 @ussoccer @opencup I want to see what their claims were against the league

1/30/2022 7:51
@taco_x86 @ussoccer @opencup NAFC will play in NISA

1/30/2022 7:54
@taco_x86 @ussoccer @opencup Yes but they want a $1m performance bond which is not the same rule for other teams which is $250k. I refuse to consent to different rules. All teams need to be playing under the same rules

1/30/2022 8:36
@NISALeague pay your bill to @ChattanoogaFC stadium from over a year ago

1/30/2022 8:37
@NISALeague pay your bill to the consultants you hired to fix @StumptownAC and then fired

1/30/2022 8:38
@NISALeague what’s the six figure AP figure the Prutch family is owed? Is it similar to the @DetroitCityFC settlement figures? Wonder what the use of those funds will be

1/30/2022 8:40
@NISALeague ,@CalUtdStrikers asked you to produce monthly financial statements this year due to John Prutch lack of transparency. We haven’t heard from you on this yet. Do you plan to comply with this request?

1/30/2022 8:58
https://t.co/XBfiXN9UIM

1/30/2022 9:01
@MarylandFooty @THEDanVaughn @jgbrass The commissioner needs to be fired so we can fix the league

1/30/2022 9:04
Us involved = NISA keeps two teams in major markets

Us not involved = two less teams and league risks falling while we play elsewhere 

Commissioner should be focused on growing league and helping teams succeed

1/30/2022 9:06
Let’s write a new constitution for @NISALeague under new leadership that acts in the interest of teams and not the Prutch family https://t.co/lW2pq0Ctd6

1/30/2022 9:07
@taco_x86 A new one or the ones you know

1/30/2022 9:08
@taco_x86 Yes

1/30/2022 9:25
@mikeireland @taco_x86 Yep if NISA screws us we will authorize an unlimited litigation war chest against them, subpoena every document they have ever written, texted or emailed - depose them all and do exactly that. See below. https://t.co/G4rZv41ZAK

1/30/2022 9:30
@NISALeague Bob Friedland at least put in the $310K you owe the league so the staff can get paid. I heard Joshy hasn’t been paid in a while

1/30/2022 10:15
@taco_x86 It is her call.

1/30/2022 10:22
@J_Kaley Waiting for them to respond to an email. They know we plan to play

1/30/2022 10:23
https://t.co/p2hmV0A89j

1/30/2022 10:56
@919zac https://t.co/Glf4r0NId7

1/30/2022 10:57
@RedTheWhiteBoy He actually turned his amateur team he was playing on into a pro team just so you are aware. Thanks! He is has been the PTO since day one.

1/30/2022 11:03
@RedTheWhiteBoy Well the PTO applies to join NISA and makes a presentation to convince the board to include them in the league, raised the capital to launch the team, meets with US Soccer, hires the staff and so forth

1/30/2022 11:04
@RedTheWhiteBoy Laurence is the primary team owner

1/30/2022 11:06
@NISALeague was an extensive interview process done to see if Josh and Sam Prutch are the best people for the job? If not, is there a set of objectives we laid out for them and can you share that with us? Did they accomplish said objectives? Same for John?

1/30/2022 11:16
@AtlGorillaTalk @NISALeague Because they know every word they say will be used against them in litigation and their leadership is poor. A real leader would call me and try and settle not ignore me for 3 weeks. John doesn’t want me in the league because he thinks I’ll convince the other teams to fire him

1/30/2022 14:50
@NISALeague @ussoccer @opencup the fans have spoken. All teams should have the same size performance bond. @ChattanoogaFC @MichiganStarsFC @MDBobcatsFC @NYCosmos @StumptownAC @FlowerCityUnion @LosAngelesForce @SyracuseAC @ALBION_SanDiego https://t.co/IJLgkV0BH8

1/30/2022 14:51
They are making us have a $1m bond everyone else including those in a more challenging financial situation are only being required to have $250k performance bond

1/30/2022 16:10
@taco_x86 @StillOnAIM @mikeireland @AtlGorillaTalk @NISALeague https://t.co/1FOP9f7OJs

1/30/2022 16:14
@jwzfootball https://t.co/CXDmA96XDt

1/30/2022 16:15
Yes we are watching US vs Canada.

1/30/2022 16:30
@ussoccer match is making NAFC and CHAC investors think about providing more funding to both @nafcnyc and @ChicagoHouse_AC this season. And then work on throwing out the prutch family.

1/30/2022 16:38
What a save!!!

1/30/2022 16:59
@nafcnyc and @ChicagoHouse_AC have decided to play this season. We shall however continue to pursue our campaign of getting the commissioner fired. If neither team plays, it’s because the commissioner is corrupt and self-serving. @NISALeague https://t.co/FFzcrzVcqU

1/30/2022 17:00
@ussoccer @opencup both need to be included in open cup IMO

1/30/2022 17:01
https://t.co/PZqWkpatU4

1/30/2022 17:01
@taco_x86 Whatever it says is a lie

1/30/2022 17:03
@taco_x86 If they release a schedule tomorrow it’s a lie or they will change it later guaranteed

1/30/2022 17:04
@taco_x86 According to who?

1/30/2022 17:05
@taco_x86 Not aware

1/30/2022 17:06
@THEDanVaughn @NISALeague @ChicagoHouse_AC Nice Dan so you want to screw over dozens of players and employees at our club?

1/30/2022 17:06
@NISALeague commissioner continues to refuse to communicate

1/30/2022 17:07
@taco_x86 He is gonna play in a league by himself soon , can’t have a league without the teams. But hey he is familiar with playing in a public park

1/30/2022 17:09
@taco_x86 Many teams want us to play. I doubt they even have 8 teams without us

1/30/2022 17:09
@mojodean @taco_x86 Many of the teams are on our side and want us to play such as Chattanooga, Michigan , etc

1/30/2022 17:15
@NISALeague John prutch is a pathological liar that needs to be fired immediately. He said “The league / football investments will be investing $1 million into chicago within 60 days.” Lying piece of shit

1/30/2022 17:16
@ramincol @THEDanVaughn @NISALeague @ChicagoHouse_AC The commissioner promised to invest $1m into chicago and lied about it

1/30/2022 17:22
Russia and Ukraine are on the brink of war but still having diplomatic and open line of communication to settle. @NISALeague commissioner John Prutch can’t call me about soccer to have a meaningful settlement discussion. Pathetic.

1/30/2022 17:34
@mojodean @taco_x86 https://t.co/CbBXBiYZRg

1/30/2022 17:36
@NISALeague minimum amount our clubs sue you for is $10 million if we aren’t included in the schedule.

1/30/2022 17:38
@NISALeague -&gt; @DetroitCityFC gone. @oaklandrootssc gone. @TheMiamiFC gone. Why - because the commissioner lies. Imagine new Amsterdam or chicago don’t play this season? You think we are going to keep our mouth shut? Good luck adding new teams without our support

1/30/2022 17:40
@NISALeague I was having a conversation with one of the expansion clubs who also felt friedland and prutch lie regularly about when and how much their entity “football investments” will be investing.

1/30/2022 17:40
@NISALeague I’m not going to say who but one of the bigger @NISALeague clubs wants friedland and prutch out. Not to mention many others

1/30/2022 17:49
@THEDanVaughn @OldBaeBrigade It’s a business matter

1/30/2022 17:58
@LeoGlickman1 @phat7deuce @THEDanVaughn @NISALeague @ChicagoHouse_AC Yup there is a plan

1/30/2022 18:00
@THEDanVaughn You sure about that statement? How much do I owe the coaches? BUONA is owed nothing and a final payment to CJ was processed this weekend

1/30/2022 18:01
@THEDanVaughn Maybe realize this was the first season with fans allowed to attend during a pandemic and the revenue projections didn’t go as we thought. We could have just not even tried to play during a pandemic … This happens all the time in business and it’s about course correcting

1/30/2022 18:03
@taco_x86 @THEDanVaughn https://t.co/6hlqOXkHr9

1/30/2022 18:15
https://t.co/rMZ56V7mqm

1/30/2022 19:01
@NISALeague said we could play this Spring if we paid our remaining league dues from last season. We didn’t pay the last $17.5K immediately bc they refused to provide league financials. Many other teams haven’t paid league dues immediately. See attached payment. https://t.co/Hr9hNnS2KK

1/30/2022 19:36
https://t.co/Mg2LLXWhZY https://t.co/WAnU1fRQqm

1/30/2022 19:44
@taco_x86 https://t.co/OJcaWCagZP

1/30/2022 20:41
@theactualsoccer @ProtagonistUSA @KnightsWhoNISA Will you buy me a pizza if you’re wrong please?

1/30/2022 21:14
@CFC_Rep Coming back soon

1/30/2022 21:28
@THEDanVaughn it's sad that we lost

1/31/2022 6:52
https://t.co/29sjQLSwSa https://t.co/P2M5FtVi8O

1/31/2022 6:56
@NISALeague https://t.co/b8Q68VYuPu

1/31/2022 7:05
Highlights from our London Trip ⁦@WestHam⁩ - I’m forever blowing bubbles chant that our club loves ⁦@LondonStadium⁩, can someone write a chant for ⁦@nafcnyc⁩ ?!?! https://t.co/aEg5USw7j1

1/31/2022 8:12
@ThaBlackUnicorn https://t.co/TSKSfdBViT

1/31/2022 9:35
@taco_x86 https://t.co/iaSOujCVcj

1/31/2022 10:02
@ThaBlackUnicorn https://t.co/UbXdLFLydJ

1/31/2022 10:48
@johnyarina @NISALeague @KevBruhh https://t.co/ajT7ZTmJL9

1/31/2022 11:35
@ManagerEnrique @LuisArreola19 @THEDanVaughn @NISALeague @ChicagoHouse_AC She doesn’t run it, Peter does

1/31/2022 13:49
@mplscitysc https://t.co/TZDHQd6bVi

1/31/2022 13:55
@NISALeague we are waiting for your phone call so we can get on with @opencup

1/31/2022 14:10
@FlowerCityUnion @yelpROC https://t.co/zkEY4ObvZs

1/31/2022 14:10
@MDBobcatsFC https://t.co/gXVuMYvVTm

1/31/2022 14:30
@valleyunitedaz @TheNISANation https://t.co/m4DBPnE3j9

1/31/2022 15:19
@NISALeague, Bob Friedland, and John Prutch appear to be trying to prevent both New Amsterdam and Chicago House from playing this season in NISA and @opencup . I just left a voicemail for @ussoccer integrity hotline reporting these issues asking them to call me back. https://t.co/5P2HUYLU66

1/31/2022 15:51
Soccer nation we need your advice here! Should New Amsterdam and Chicago play in @NISALeague under the poor leadership of John Prutch + try to fire him later or start our own league registered as a non-profit where all teams are truly created equally and have an equal voice?

1/31/2022 15:52
@ChattaGooner @NISALeague @opencup honestly it is so good the grilled chicken with some of that spicy sauce and the watermelon we had it all the time when we lived here!

1/31/2022 15:55
@alerodr24 @NISALeague tell them to give us a call 

1/31/2022 16:17
https://t.co/MbTpGg56hR

1/31/2022 16:26
@NISALeague commissioner John Prutch learn about this plz: "A lie is an assertion that is believed to be false, typically used with the purpose of deceiving someone. The practice of communicating lies is called lying. A person who communicates a lie may be termed a liar." https://t.co/AR77Dtwlob

1/31/2022 16:28
@phat7deuce Plus of course revenue

1/31/2022 16:28
@phat7deuce We are funded through a combination of angel investors + sponsorship from Fruit Street! Maybe you missed this press release that is publicly available: https://t.co/IV82P1dVjc

1/31/2022 16:34
@phat7deuce Fruit Street is a public benefit corporation that delivers virtual classes with dietitians that promote a healthy lifestyle. FS decided to sponsor and help create a club in our community bc sport also promotes a healthy lifestyle amount adults and kids in our youth academy.

1/31/2022 16:37
@Murricles @NISALeague https://t.co/KRInqQs4XT

1/31/2022 17:13
I want to say that despite not believing in the commissioner of @NISALeague, our club really believes in the concept of the league and we feel that the other owners of the league are amazing human beings that can help grow the game in this country. Thank you to all of the clubs!

1/31/2022 17:26
https://t.co/Th5YEEjGqe

1/31/2022 17:38
Our new mascot for @nafcnyc! https://t.co/UzDtqI8Tsl

1/31/2022 17:39
https://t.co/xtXBZ0iGTC

1/31/2022 19:57
@phat7deuce @vegitalist @taco_x86 Ty for question. FS owns some shares in New Amsterdam and is a debt financing partner and sponsor as well to answer your question. FS is a public benefit corporation that in addition to being a for profit entity has a social impact on the community and youth via soccer.

1/31/2022 20:06
@taco_x86 @phat7deuce @vegitalist We raised at $2.5M pre and have raised around $1m

1/31/2022 20:11
@taco_x86 @phat7deuce @vegitalist No we have dozens of angel investors who invested 25-250k each a lot of doctors

1/31/2022 20:15
@taco_x86 @phat7deuce @vegitalist The doctors and angels invested over $1m

1/31/2022 20:17
@taco_x86 @phat7deuce @vegitalist NAFc

1/31/2022 20:21
@phat7deuce @taco_x86 @vegitalist it’s a very small item on FS budget

1/31/2022 20:22
@taco_x86 @phat7deuce @vegitalist I said around $1M. And also these documents don’t get updated in real time that’s not how a 506c offering works, and it’s not required to be updated in real time

1/31/2022 20:24
@taco_x86 @phat7deuce @vegitalist You’ll see it one day when we do a reg CF

2/1/2022 12:48
@taco_x86 @phat7deuce @vegitalist I will give you exact number this week been traveling

